version: '3.8'

services:
  web:
    build: ./to_do
    command: python3 manage.py runserver 0.0.0.0:8000
    volumes:
      - ./to_do/:/usr/src/to_do/
    ports:
      - 8000:8000
    env_file:
      - ./.env
    depends_on:
      - db
  db:
    image: postgres:15
    volumes:
      - postgres_data:/var/lib/postgresql/data/
    environment:
      - POSTGRES_USER=${SQL_USER}
      - POSTGRES_PASSWORD=${SQL_PASSWORD}
      - POSTGRES_DB=${SQL_DATABASE}

volumes:
  postgres_data: