# Generated by Django 4.2.3 on 2023-09-14 15:16

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('task', '0002_task_user'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='task',
            name='user',
        ),
    ]
