# Generated by Django 4.2.3 on 2023-09-14 15:30

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('task', '0004_task_user'),
    ]

    operations = [
        migrations.RenameField(
            model_name='task',
            old_name='user',
            new_name='created_by',
        ),
    ]
